name: Welcome Message

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest
    
    steps:
      - name: Welcome new contributor
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            👋 Спасибо за создание первого issue! 
            
            🏗️ **PRIME360.AI** - это система управления строительными проектами.
            
            Мы рассмотрим ваше сообщение в ближайшее время.
            
            📚 Ознакомьтесь с [документацией](../README.md) для получения дополнительной информации.
            
          pr-message: |
            👋 Спасибо за ваш первый Pull Request!
            
            🎉 Мы ценим ваш вклад в **PRIME360.AI**!
            
            Пожалуйста, убедитесь, что:
            - ✅ Код следует стилю проекта
            - ✅ Все файлы корректно работают
            - ✅ Обновлена документация (если необходимо)
            
            Мы скоро рассмотрим ваши изменения!

